ceredigion-clp/app/module_admin/models.py
from ceredigionclp import db, bcrypt
from sqlalchemy.ext.hybrid import hybrid_property
from hashlib import md5

class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    creation_date = db.Column(db.DateTime, default=db.func.current_timestamp())
    modification_date = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

class User(Base):
    __tablename__ = "auth_user"
    user_name = db.Column(db.String(64), unique=True, nullable=False)

    password_hash = db.Column(db.String(128), nullable=False)

    email_address = db.Column(db.String(128), unique=True)

    @hybrid_property
    def password(self):
        return self.password_hash

    @password.setter
    def _set_password(self, plaintext):
        self.password_hash = bcrypt.generate_password_hash(plaintext)

    def is_correct_password(self, plaintext):
        if bcrypt.check_password_hash(self._password, plaintext):
            return True
        else:
            return False

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def avatar(self, size):
        return 'https://www.gravatar.com/avatar/%s?d=mm&s=%d' % (
        md5(self.email_address.encode('utf-8')).hexdigest(), size)

    def __repr__(self):
        return self

ceredigion-clp/app/module_events/models.py
from ceredigionclp import db

class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    creation_date = db.Column(db.DateTime, default=db.func.current_timestamp())
    modification_date = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

class Event(Base):
    __tablename__ = "events"
    title = db.Column(db.String(64), unique=False, nullable=False)
    description = db.Column(db.String(2048), unique=False, nullable=True)
    venue = db.Column(db.String(64), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)

ceredigion-clp/app/module_minutes/models.py
from ceredigionclp import db

class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    creation_date = db.Column(db.DateTime, default=db.func.current_timestamp())

class Minute(Base):
    __tablename__ = "minutes"
    source = db.Column(db.String, nullable=False)
    pdf = db.Column(db.LargeBinary, nullable=False)
    odt = db.Column(db.LargeBinary, nullable=False)
    date = db.Column(db.DateTime, nullable=False)

ceredigion-clp/app/module_admin/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField("Username", [DataRequired("You need to provide a username")])
    password = PasswordField("Password", [DataRequired("You need to provide a password")])

ceredigion-clp/app/module_admin/controllers.py
from flask import Blueprint, request, render_template, flash, g, abort, redirect, url_for

from flask_login import login_user, logout_user, current_user, login_required


from module_admin.models import User
from module_admin.forms import LoginForm

from ceredigionclp import app, db, bcrypt, login_manager

admin = Blueprint("admin", __name__, url_prefix="/admin")

@admin.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(user_name = form.username.data).first()
        if user and user.is_correct_password(form.password.data):
            return "Logged In"
    else:
        flash("Hello World")
    return render_template("admin/login.html", form=form)

@admin.route("/test", methods=["GET", "POST"])
def create_admin():
    user = User(
        user_name = "admin",
        password = "password",
        email_address = "email@email.com"
    )

    db.session.add(user)
    db.session.commit()
    return "Admin Created"

ceredigion-clp/app/module_events/controllers.py
from flask import Blueprint, jsonify, render_template, flash, g, abort, redirect, url_for

from module_events.models import Event

from ceredigionclp import app, db, bcrypt, login_manager, Map

events = Blueprint("events", __name__, url_prefix="/events")

@events.route("/", methods=["GET", "POST"])
def index():

    map = Map(
        identifier="catsmap",
        lat=37.4419,
        lng=-122.1419,
        style="height:95%;width:100%;max-height:500px;",
        markers=[
            {
                'icon': 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
                'lat':  37.4419,
                'lng':  -122.1419,
                'infobox': "B"
            },
            {
                'icon': 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                'lat': 37.4300,
                'lng': -122.1400,
                'infobox': "B"
            },
            {
                'icon': 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png',
                'lat': 37.4500,
                'lng': -122.1350,
                'infobox': "B"
            }
        ]
    )

    return render_template("events/index.html", map=map)

@events.route("/api/", methods=["GET"])
def events_api():
    j = [{
        "Name" : "North Branch Meeting",
        "Description" : "Description",
        "Location" : "Morlan Centre",
        "Date" : "11/02/18",
        "Time" : "6:30pm",
        "Latitude" : 52.41634,
        "Logitude" : -4.080294
    }]
    return jsonify(j)

ceredigion-clp/app/module_minutes/controllers.py
from flask import Blueprint, jsonify, render_template, flash, g, abort, redirect, url_for

from module_minutes.models import Minute

from ceredigionclp import app, db, login_manager

minutes = Blueprint("minutes", __name__, url_prefix="/minutes")

@minutes.route("/", methods=["GET", "POST"])
def index():
    return render_template("minutes/index.html")

ceredigion-clp/app/templates/branches.html
{% extends "template.html" %}

{% block page_title %}Branches{% endblock %}

{% block body %}

  <div class="page-content">
    <h1>Branches</h1>

    <p>The Ceredigion Labour party is made up of two Branches so that we can
      engage more easily with members of our community. Both Branches have members
      who are elected representatives of their communities.</p>

    <p>The two Branches come together every month as a Constituency to discuss matters
      concerning Ceredigion as a whole and how best to fight for improvements to our area.
      For more information on these meetings, please contact your local Branch Secretary.</p>

    <h2>South Ceredigion Labour Party Branch</h2>

    <p>The South branch is in the process of reforming and we have started to
      arrange monthly social meetings in Cardigan Town.</p>

    <h2>Aberystwyth and North Ceredigion Labour Party Branch</h2>

    <p>The Aberystwyth and North Ceredigion Branch serves the north of Ceredigion
      and meets regularly for campaigning events. Please contact Alex Mangold (Branch Secretary)
      on ceredigionlabour.northbranch@gmail.com if you would like to find out more about the
       Aberystwyth and North Ceredigion Branch.</p>
  </div>

{% endblock %}

ceredigion-clp/app/templates/events/index.html
{% extends "template.html" %}

{% block page_title %}Events{% endblock %}

{% block body %}
  <div class="page-content">
    <h1>Events</h1>
    {{ map.html }}
    <p>Table goes here.</p>
  </div>
{% endblock %}

{% block javascript %}
{{ map.js }}
{% endblock %}

ceredigion-clp/app/templates/index.html
{% extends "template.html" %}

{% block page_title %}Home{% endblock %}

{% block body %}

<div id="homepage-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="carousel-caption d-none d-md-block">
        <h1>For the many, not the few</h1>
      </div>
      <img class="d-block w-100" src="https://ceredigionlabour.files.wordpress.com/2017/04/cardigan1.jpg?w=1024" alt="First slide">
    </div>
  </div>
</div>
  <div class="page-content">
    <div class="row">
      <div class="col-sm-8">

        <blockquote class="blockquote">
          <p class="mb-0">"At the heart of all we do will be our determination to fight for jobs
            and grow the Welsh economy. Ours is an ambitious, positive vision of the
            nation we can become. In everything we do we will stand up for Wales and
            lead our country forward with ambition."</p>
          <footer class="blockquote-footer">Carwyn Jones AM</footer>
        </blockquote>

        <p>Labour has only been in government for four short periods of the 20th
          century. However its achievements have revolutionised the lives of the
          British people. The values Labour stands for today are those which have
          guided it throughout its existence.</p>

        <ul>
          <li>social justice</li>
          <li>strong community and strong values</li>
          <li>reward for hard work</li>
          <li>decency</li>
          <li>rights matched by responsibilities</li>
        </ul>

        <p>The Labour Party in Ceredigion has elected representatives at every level
           of Government, from Assembly Members and Members of the European Parliament
           to our hard-working County and Community Councillors. The Ceredigion Labour Party
           has worked passionately to improve the lives of those in our communities and will
           continue to do so, even in the face of the Coalition’s disastrous economic policies.</p>
      </div>
      <div class="col-sm-4">
        <h3>LATEST NEWS</h3>
      </div>
    </div>
  </div>

{% endblock %}

ceredigion-clp/app/templates/minutes/index.html
{% extends "template.html" %}

{% block page_title %}Minutes{% endblock %}

{% block body %}
  <div class="page-content">
    <h1>Minutes</h1>

    <p>Table goes here.</p>

  </div>


{% endblock %}

ceredigion-clp/app/templates/template.html
<html>

<head>
  <link href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/global.css')}}" rel="stylesheet">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='imgs/favicon.ico')}}"/>

  <title>{% block page_title %}{% endblock %} : Ceredigion Labour Party</title>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index')}}">Ceredigion CLP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('events.index')}}">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('minutes.index')}}">Minutes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('branches')}}">Branches</a>
      </li>
    </ul>
  </div>
</nav>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <p>Promoted by Rachel Seabrook, Secretary, Ceredigion CLP, on behalf
              of Ceredigion CLP, at Smelting Cottage, Devil’s Bridge, Ceredigion,
               SY23 4QY</p>
          </div>
          <div class="col-sm-4">
            <p>Instagram and Facebook stuff here</p>
          </div>
        </div>
      </div>
    </footer>
</body>


<!-- Javascript Imports -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>

{% block javascript %}


{% endblock %}

</html>